version: '3.8'

services:
  db:
    container_name: kxn_db_ora
    environment:
      ORACLE_PWD: oracle
    image: konnexionsgmbh/db_19_3_ee:latest
    networks:
      - kxn_net
    ports:
      - "1521:1521"
    
  dev:
    command: /bin/bash -c "
      while [ `docker inspect -f {{.State.Health.Status}} kxn_db_ora` != 'healthy' ]; do docker ps --filter 'name=kxn_db_ora'; sleep 60; done
      && sqlplus sys/oracle@kxn_db_ora:1521/orclpdb1 as sysdba @/usr/bin/run_db_setup.sql
      && git clone https://walter-weinmann:6151c6a8fb817c50c88856d02c14d7a3bfea8557@github.com/KonnexionsGmbH/dderl.git
      && cd dderl
      && ./build_fe.sh
      && rebar3 shell
      "
    container_name: kxn_dev
    depends_on:
      - db
    image: konnexionsgmbh/kxn_dev:latest
    networks:
      - kxn_net
    ports:
      - "8443:8443"
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  kxn_net:
