FROM erlang:22.3-slim as base

# Supplement necessary system software -----------------------------------------
RUN apt-get update \
 && apt-get install -yq  

RUN apt-get install -yq alien \
                        autoconf \
                        autotools-dev \ 
                        build-essential \
                        curl \
                        git \
                        openssl \
                        procps \
                        wget \
 && git config --global credential.helper 'cache --timeout 3600' \
 && wget https://download.oracle.com/otn_software/linux/instantclient/19600/oracle-instantclient19.6-basic-19.6.0.0.0-1.x86_64.rpm \
 && alien -i *.rpm \
 && wget https://s3.amazonaws.com/rebar3/rebar3 \
 && chmod +x rebar3 \
 && mv rebar3 /usr/bin \
 && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \ 
 && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
 && apt-get update \
 && apt-get install -y yarn

RUN apt-get install -y dos2unix \
                       htop \
                       tmux \
                       vim

# Setting Environment Variables ------------------------------------------------
ENV ERL_INTERFACE_DIR=/usr/local/lib/erlang/lib/erl_interface-3.13.2 \
    ORACLE_HOME=/usr/lib/oracle/19.6/client64
 
RUN echo "=====================================================================> Curent Date: " \
 && date \
# Show Environment Variables ---------------------------------------------------
 && echo "=====================================================================> Environment variable ERL_INTERFACE_DIR: " \
 && echo $ERL_INTERFACE_DIR \
 && echo "=====================================================================> Environment variable ORACLE_HOME: " \
 && echo $ORACLE_HOME \
# Show component versions ------------------------------------------------------
 && echo "=====================================================================> Version  autoconf: " \
 && autoconf -V \
 && echo "=====================================================================> Version  automake: " \
 && automake --version \
 && echo "=====================================================================> Version  curl: " \
 && curl --version \
 && echo "=====================================================================> Version  debian: " \
 && cat /etc/os-release \
 && echo "=====================================================================> Version  dos2unix: " \
 && dos2unix --version \
 && echo "=====================================================================> Version  gcc: " \
 && gcc --version \
 && echo "=====================================================================> Version  Git: " \
 && git --version \
 && echo "=====================================================================> Version  htop: " \
 && htop --version \
 && echo "=====================================================================> Version  openssl: " \
 && openssl version -a \
 && echo "=====================================================================> Version  procps-ng: " \
 && ps --version \
 && echo "=====================================================================> Version  rebar3: " \
 && rebar3 version \
 && echo "=====================================================================> Version  tmux: " \
 && tmux -V \
 && echo "=====================================================================> Version  vim: " \
 && vim --version \
 && echo "=====================================================================> Version  wget: " \
 && wget --version \
 && echo "=====================================================================> Version  yarn: " \
 && yarn --version 

EXPOSE 1236 \
       7000 7001 7002 7003 7004 7005 7006 7007 7008 7009 \
       7010 7011 7012 7013 7014 7015 7016 7017 7018 7019 \
       7020 8125 8443 9443

CMD ["/bin/bash"]
